"""Add image_url to Project model

Revision ID: 07afda7495db
Revises: e12b154665a0
Create Date: 2025-05-16 11:06:05.687749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07afda7495db'
down_revision = 'e12b154665a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
